variables:
  ACR: 'YOURACR.azurecr.io'

steps:
- task: Kubernetes@1
  displayName: 'Create Deployments & Services in AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Pay-As-You-Go (4b652faa-7b9c-42a8-ab03-a74ce1188278)'
    azureResourceGroup: sampkle
    kubernetesCluster: sample
    command: apply
    useConfigurationFile: true
    configuration: '$(System.DefaultWorkingDirectory)/MyHealth.AKS.build/deploy/mhc-aks.yaml'
    azureContainerRegistry: '$(ACR)'
    secretName: mysecretkey
    versionSpec: 1.8.1
    checkLatest: true
